name: Build and Push to DigitalOcean Registry

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        logout: false

    - name: Validate secrets
      run: |
        if [ -z "${{ secrets.DIGITALOCEAN_REGISTRY }}" ]; then
          echo "Error: DIGITALOCEAN_REGISTRY secret is not set"
          echo "Please add DIGITALOCEAN_REGISTRY=socioh-librechat-registry to your GitHub secrets"
          exit 1
        fi
        
        echo "Registry: ${{ secrets.DIGITALOCEAN_REGISTRY }}"
        echo "Image will be pushed to: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY }}/slack-mcp-server:latest"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY || 'socioh-librechat-registry' }}/slack-mcp-server:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY || 'socioh-librechat-registry' }}/slack-mcp-server:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY || 'socioh-librechat-registry' }}/buildcache,mode=max

    - name: Verify image in registry
      run: |
        echo "Verifying image exists in registry..."
        docker pull ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY || 'socioh-librechat-registry' }}/slack-mcp-server:latest
        echo "✅ Image successfully pushed to registry"
        echo "Image location: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY }}/slack-mcp-server:latest" 