name: Deploy to DigitalOcean

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: registry.digitalocean.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        logout: false

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY }}/slack-mcp-server:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY }}/slack-mcp-server:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ secrets.DIGITALOCEAN_REGISTRY }}/slack-mcp-server:buildcache,mode=max

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Deploy to DigitalOcean App Platform
      run: |
        # Create a new service spec to add to existing app
        cat > new-service-spec.yaml << EOF
        services:
        - name: slack-mcp-server
          image:
            registry_type: DOCR
            registry: ${{ secrets.DIGITALOCEAN_REGISTRY }}
            repository: slack-mcp-server
            tag: latest
          instance_count: 1
          instance_size_slug: basic-xxs
          # Internal port only - not exposed publicly
          internal_ports:
          - 3001
          envs:
          - key: SLACK_MCP_HOST
            value: "0.0.0.0"
          - key: SLACK_MCP_PORT
            value: "3001"
        EOF
        
        # Add the new service to the existing app using the app ID
        doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }} --spec new-service-spec.yaml
        
        echo "Successfully added slack-mcp-server component to existing app" 